version: '3.4'

services:
  majorappservice:
    image: wordpress
    ports:
      - "8080:80"
    depends_on:
      - mysql

    environment:
       WORDPRESS_DB_USER : root
       WORDPRESS_DB_PASSWORD : "Password123"
       WORDPRESS_DB_HOST : "mysql"
       WORDPRESS_DB_NAME : testdb

      

## mysql ddddd

  mysql:
    image: mysql:5.7  
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: "Password123"
    

      